  Seq2SeqTrainingArgs = Seq2SeqTrainingArguments(
      output_dir="./results",
      per_device_train_batch_size=2,
      per_device_eval_batch_size=2,
      num_train_epochs=3,
      eval_steps=500,
      save_total_limit=2,
      logging_steps=100,
      save_strategy="steps",
      remove_unused_columns=False,
      gradient_accumulation_steps=1, 
      predict_with_generate=True,
      generation_max_length=48,
      generation_num_beams=3,
  )